### PR TITLE
add formal description to readme

### PR DESCRIPTION
**Pull request by manzt**
cc @joshmoore

### CODE REVIEW

**Comment by ilan-gold** [comment]
As a general comment, I'm hesistant to attach the "ome" suffix here. I should have commented on this in the other PR but I actually think that what I built is OME-independent on purpose.  I will comment on the other PR.

**Comment by manzt** [comment]
While I agree the approach generalizes to all TIFFs, the only readers that recognize the offsets "spec" are tailored towards OME-TIFF. Additionally, both python CLI and website are hard-coded to replace`ome.tiff/ome.tif` suffixes. This can of course be changed, but I since seeing this note earlier about (avoidance) of explicit storing of offsets in TIFF, 

> "One thing to keep in mind about Indexed OME-TIFF: “the TIFF specification explicitly forbids tag data to include any offsets into the file or into any other TIFF data block, except for the documented special cases (TileOffsets, StripOffsets,...). This enables total relocatability of all structures and data blocks” (https://www.awaresystems.be/imaging/tiff/faq.html)

I wonder how many client implementations would actually accept support for offsets like this. We are fortunate that we have been able to introduce this functionality in `geotiff` without modifying the geotiff source code.

**Comment by ilan-gold** [comment]
I suppose it's just a presentation thing - people in the `geotiff` community might be interested in this as well for exactly the reason we are interested in it.  Presenting it is OME-specific is a bit misleading.  I don't feel too strongly about this in general if we want to talk about OME as the motivator, but I will sat that I don't want people to read this and think it's somehow special for OME-TIFFs.  It's for any TIFF file.

**Comment by manzt** [comment]
Ok, I don't really mind either way.  We've only evaluated this method on OME-TIFF, however, so I've clarified that in the README and website.

**Pull request merged**
